# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         autobox
version:      0.07
version_from: lib/autobox.pm
installdirs:  perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
