# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         autobox
version:      2.42
version_from: autobox.pm
installdirs:  perl
license:      perl
requires:
    Scope::Guard:                  0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
