--- #YAML:1.0
name:                autobox
version:             2.55
abstract:            call methods on native types
license:             perl
author:              
    - chocolateboy <chocolate.boy@email.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Scope::Guard:                  0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
